config/routes.rb
Rails.application.routes.draw do

  root :to => "landing#index"

  get "home" => 'kiwis#show'

  get "health" => "kiwis#health"

  resources :kiwis

  resources :settings do
    collection do
      get 'personal'
      get 'social'
      get 'profile'
    end
  end

  resources :profiles, only: [:index]

  resources :accounts

  resources :products do
    collection do
      put 'buy'
      put 'reset'
    end
  end


  resources :identities, only: [:index] do
    collection do
      get 'sign_up'
      get 'login'
      get 'authorisation'
      put 'logout'
      get "test"
    end
  end

  namespace :api do
    namespace :v1 do
      resources :kiwis
      resources :api_docs
    end
  end


end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  
  def index
    @kiwi = @current_user_proxy.kiwi
  end
  
  def personal
    @kiwi = @current_user_proxy.kiwi
    
  end

  def social
    @kiwi = @current_user_proxy.kiwi    
  end
  
  def profile
    profiler_service = ProfilerAdapter.new.profiler_url(host: request.host_with_port, user_proxy: @current_user_proxy)
    redirect_to profiler_service
  end

  
end

app/views/settings/_icon_bar.html.erb
<div class="icon-bar large-vertical four-up">
   <%= link_to(personal_settings_path, class: "item", remote: true) do %>
      <i class="fi-torso"></i>
      <label>Personal</label>
   <% end %>
   <%= link_to(social_settings_path, class: "item", remote: true) do %>
       <i class="fi-social-500px"></i>       
      <label>Social</label>
   <% end %>
   <%= link_to(profile_settings_path, class: "item") do %>
       <i class="fi-social-500px"></i>       
      <label>Profile</label>
   <% end %>
   
   
</div>

app/views/settings/index-old.html.erb
<dl class="accordion" data-accordion>
  <dd class="accordion-navigation">
    <a href="#panel1">
       <i class="fi-torso"></i>
       Personal       
    </a>
    <div id="panel1" class="content active">
       <%= render partial: "kiwis/personal"%>
    </div>
  </dd>
  <dd class="accordion-navigation">
    <a href="#panel2">
       <i class="fi-social-500px"></i>       
       Social
    </a>
    <div id="panel2" class="content">
       <%= render partial: "kiwis/social"%>    
    </div>
  </dd>
  <dd class="accordion-navigation">
    <a href="#panel3">Security</a>
    <div id="panel3" class="content">
      Panel 3. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
  </dd>
  <dd class="accordion-navigation">
    <a href="#panel4">
       <i class="fi-torso"></i>
       Profile       
    </a>
    <div id="panel4" class="content active">
       <%= link_to "Profile", profiles_path(kiwi: @kiwi), class: "button"%>
    </div>
  </dd>
  
</dl>

app/views/settings/index.html.erb
<div class="row">
   <div class="small-3 columns">
      <%= render "icon_bar"%>
   </div>
   <div class="small-9 columns">
      <div id="settings-content"></div>
   </div>
</div>