config/routes.rb
Rails.application.routes.draw do

  root :to => "landing#index"

  get "home" => 'kiwis#show'

  get "health" => "kiwis#health"

  resources :kiwis

  resources :settings do
    collection do
      get 'personal'
      get 'social'
      get 'profile'
    end
  end

  resources :profiles, only: [:index]

  resources :accounts

  resources :products do
    collection do
      put 'buy'
      put 'reset'
    end
  end


  resources :identities, only: [:index] do
    collection do
      get 'sign_up'
      get 'login'
      get 'authorisation'
      put 'logout'
      get "test"
    end
  end

  namespace :api do
    namespace :v1 do
      resources :kiwis
      resources :api_docs
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = ProductsManager.all.products
  end
  
  def buy
    prod = ProductsManager.new(product_origination_url: params[:prod_origination_url], kiwi: @current_user_proxy.kiwi)
    prod.subscribe(self)
    prod.buy
  end
  
  def successful_purchase_event(product)
    redirect_to products_path
  end
  
  def reset
    prod = ProductsManager.new(kiwi: @current_user_proxy.kiwi)
    prod.subscribe(self)
    prod.reset(params)
  end
  
  def reset_complete
    redirect_to products_path
  end
  
end

app/views/products/index.html.erb
<table>
  <thead>
    <tr>
      <th>Product</th>
      <th></th>
    </tr>
  </thead>
   <tbody>
      <% @products["sales_products"].each do |prod|%>
         <% purch = @kiwi.get_purchase(product: prod) %>
         <tr>
            <td><%= prod["name"]%></td>
            <% if purch %>
               <td>
                  <div data-alert class="alert-box secondary">
                       <%= purch.purchase_state %>
                    <a href="#" class="close">&times;</a>
                  </div>
               </td>
            <% else %>
               <td><%= link_to "Buy", buy_products_path(prod_origination_url: prod["_links"]["product_originations"]["href"]), class: "button", method: :put%></td>
            <% end %>
         </tr>
      <% end %>
   </tbody>
</table>

<%= link_to 'Reset All', reset_products_path, method: :put, class: "button"%>
<%= link_to 'Reset Local', reset_products_path(local: true), method: :put, class: "button"%>